spring:
  cloud:
    gateway:
      routes:
        - id: uom-service
          uri: lb://UNIT-OF-MEASURE-SERVICE
          predicates:
            - Path=/api/v1/uom/**, /api/v1/uom-status/**, /config-server-test/uom/**
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/v1/inventory-item/**
            - Path=/config-server-test/inventory/**
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      version: 1.0.0
      environment: development
      region: us-east
    prefer-ip-address: true